### ISSUE TITLE
Replacing redirections

### ISSUE THREAD

**Issue by buechlerpro** [brrrrrrrt/brt_videourlreplace#6]
When the editor text contains https://www.youtube.com/yt/about/de/ a non working video is embedded. This url shouldn't be replaced. An example text might look as following:

Weitere Informationen zu YouTube können unter https://www.youtube.com/yt/about/de/ abgerufen werden.

**Comment by buechlerpro** [comment]
Great, thank you very much!

**Comment by brrrrrrrt** [comment]
just released the new version, defaults should work in your case.

should soon be accessible in the TYPO3 Repository
